### PR TITLE
Make compatible with Marionette 2

### PR DESCRIPTION
**Pull request by just-boris**
Thanks for the excellent library! It makes work with tabs easier.

Latest Marionette has changed some of its APIs, so we need to support these changes too.

### CODE REVIEW

**Comment by kirach** [comment]
Hey @just-boris!

Thanks for you PR. We made some minor changes in our codebase. Could you please rebase your branch on the latest master and also change the version to be 2.0.0. We want to have two separate major versions of this plugin for marionette 1.x and 2.x.

Thanks!

**Comment by just-boris** [comment]
@kiRach done

**Comment by kirach** [comment]
@sakabako Are you ok with these changes? I think we can merge and make release 2.0.0

**Comment by stutrek** [comment]
:+1: Looks great. Thanks @kiRach and @just-boris

**Pull request merged**
